### ISSUE TITLE
Add OpenGraph meta tags to all the pages!

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/zeus.ugent.be#315]
Metadata is cool for when you share links!

- [ ] Project
- [ ] Projecten overview page
- [x] Event
- [ ] Event overview page (eg. last event, or a description)
- [x] Blog
- [ ] Blog overview page (eg. last blog, or a description)

**Comment by mcbloch** [comment]
https://ogp.me/

**Comment by Robbe7730** [comment]
I'm not a fan of the 'last event', as that will change over time but that's not what OpenGraph was made for
